### ISSUE TITLE
No such file or directory php.sock

### ISSUE THREAD

**Issue by Smallinger** [mll-lab/passwork-docker-compose#2]
[crit] 3232#3232: *1 connect() to unix:/var/run/php/php.sock failed (2: No such file or directory)

**Comment by spawnia** [comment]
I don't think anyone will be able to provide useful feedback based on the very limited information you have given here. If you want free help, you need to put in more effort.

**Comment by Smallinger** [comment]
Ok, form start
i try to install passwork over the docker-compose file.
After the first Installation and updating the "site" packages i run the setup.sh like in your setup description, docker give me the feedback that all is running i try to reach the webseite but got a "502 Bad Gateway" error.

I open the nginx.log and see the error above.

I go into the passwork/php7 container and open a bash console so that i can go into the folder "/var/run/php/" an see that there is no "php.sock" i look at the moment why there is no file, and try others methods.

**Comment by spawnia** [comment]
We have not hit that error in our installation, things worked fine when following the instructions outlined in the README. It looks like the image has not changed either in the meantime, see https://hub.docker.com/r/passwork/nginx-php7/tags

If you can spot the cause of the error, it would be great if you can post that here. I would be happy to include extra documentation or maybe fix the setup if needed. Thank you

**Comment by Smallinger** [comment]
soo, after a fresh install of my OVH hosted, Debain 10 Buster Server, and setup a Ubuntu VM.
and retry to install over your docker-compose file.
i got the same error on two machines.
i was looking into the container if php7.2-fpm starting and after

docker-compose exec web bash
service php7.2-fpm status 
 * php-fpm7.2 is not running

i try to start it manuel
 * Restarting PHP 7.2 FastCGI Process Manager php-fpm7.2                                                                                                                                                                [fail]

i think something with the fpm configs file are not corrent, the problem is i got no error logs from php7.2-fpm in the php log folder.
so i check the container /var/log/ folder but no logs from php7.2-fpm there too.

I have not changed anything and have followed the instructions very closely.

**Comment by Smallinger** [comment]
got it working... 
after deleting the 20-phalcon.ini in /etc/php/7.2/fpm/conf.d, fpm was starting without any problems...
so i install phalcon manuel new in the container and no props...

**Comment by spawnia** [comment]
@Smallinger nicely done. Do you think that we can fix this part in the setup, or does it require changing the base image?

We might want to take up this issue at https://github.com/passwork-me/docker

**Comment by spawnia** [comment]
I just did a fresh install with https://github.com/passwork-me/docker, things were working fine. I think they resolved the issue.
